### ISSUE TITLE
call package functions directly

### ISSUE THREAD

**Issue by matiasandina** [HeathRossie/dlcpr#3]
Hi,
Thank you so much for taking the time to make this package for reading DLC data into R.

I wanted to suggest using `data.table::fread()` instead of `fread()` type of calls.
In this way, it's more explicit, and the amount of conflicts that might happen due to having multiple packages attached is minimized. For example, if calling `library(data.table)` after `library(tidyverse)` gives:

```
Attaching package: ‘data.table’

The following objects are masked from ‘package:dplyr’:

    between, first, last

The following object is masked from ‘package:purrr’:

    transpose
``` 

I am happy to PR if needed

**Comment by HeathRossie** [comment]
Hi Mathias,

Thank your for your suggestion.
I have made a change on read.dlc() function as you suggested.

**Comment by matiasandina** [comment]
Awesome, thanks!
